import 'package:flutter/material.dart';
import 'package:manifesto/common/resources/app_resources/app_colors.dart';

import '../../../../common/resources/app_resources/app_sizes.dart';
import '../../../../common/resources/app_resources/app_text_styles.dart';
import '../../../../common/widgets/shadow_container.dart';

class RVitalSignBanner extends StatelessWidget {
  const RVitalSignBanner({super.key});

  @override
  Widget build(BuildContext context) {
    return RShadowContainer(
      child: AspectRatio(
        aspectRatio: 1.3,
        child: Container(
          padding: EdgeInsets.all(AppSizes.w20),
          color: AppColors.primary,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Icon(
                size: AppSizes.v40,
                Icons.bar_chart,
                color: AppColors.white,
              ),
              Text(
                "BIOMETRIC AUDIT",
                style: AppTextStyles.geistExtraLargeMedium
                    .copyWith(color: AppColors.white),
              ),
              Text(
                "These markers influence 84% of the curated health insights generated by our engine.",
                style: AppTextStyles.geistMediumRegular
                    .copyWith(color: AppColors.white),
              )
            ],
          ),
        ),
      ),
    );
  }
}
